version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "pricepatrol/maintainers"
    assignees:
      - "pricepatrol/maintainers"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "@types/*"
          - "@typescript-eslint/*"
          - "eslint*"
          - "vitest*"
          - "typescript"
      production-dependencies:
        dependency-type: "production"